### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/DataPackage.jl#1]
# Description

This issue documents the initial steps to get started with a new Frictionless Data implementation.

# Tasks

- [ ] Travis configuration
- [ ] Coveralls configuration
- [ ] Basic setup of README with badges
- [ ] Basic setup of license
- [ ] Review the whole family of [specifications](http://specs.frictionlessdata.io)
- [ ] Review the [implementation notes](http://specs.frictionlessdata.io/implementation/)
- [ ] Review either the Python ([Data Package](https://github.com/frictionlessdata/datapackage-py) [Table Schema](https://github.com/frictionlessdata/tableschema-py)) or JavaScript ([Data Package](https://github.com/frictionlessdata/datapackage-js) [Table Schema](https://github.com/frictionlessdata/tableschema-js)) reference implementations (whichever language you feel most comfortable reading)
  - [ ] Note that we have high nineties test coverage on these libraries. Similar test coverage is expected here
- [ ] Review the [stack reference](https://github.com/frictionlessdata/stack#frictionless-data-stack)
- [ ] Review the blog post that announces [v1 of the specifications](https://blog.okfn.org/2017/09/05/frictionless-data-v1-0/)
- [ ] Review the test packages that can be used to [test your work](https://github.com/frictionlessdata/testsuite-py/tree/master/datasets) (in addition to the normal and expected unit tests)
- [ ] Review the [OKFN Coding Standards](https://github.com/okfn/coding-standards)
  - Parts of the coding standard are language specific, and parts are workflow specific. The workflow points are important for you. If you want to contribute language-related standards to our docs for your language, we welcome it!
- [ ] Write a set of high-level issues for each library, on the respective issue tracker, that outline the work plan
  - Note the structure of this issue: A narrative description and a specific list of tasks. Follow a similar pattern
  -  The sequence of work is important: start with the Table Schema library first, as the Data Package library has a direct dependency on it
- [ ] Note the communication protocol for this work: All communication around the implementation must be in public. We want our work dynamic here to serve as an example for other implementors, and to share as much information as possible. There are two channels of communication:
  - GitHub Issues on tableschema-{LANG} and datapackage-{LANG}
  - Gitter chat at https://gitter.im/frictionlessdata/chat where all the core team at OKI are available for assistance
- [ ] Note the staff from OKI who are here to support you:
  - [Jo Barratt](https://github.com/jobarratt) - Project Manager for Frictionless Data
  - [Evgeny Karev](https://github.com/roll) - Tech Lead for core Frictionless Data libraries
  - [Serah Rono](https://github.com/callmealien) - Developer Advocate at Open Knowledge International, Dissemination Lead for the Tool Fund
  - [Dan Fowler](https://github.com/danfowler) - Developer Advocate at Open Knowledge International, Pilot Lead for Frictionless Data, OKI Labs Lead
  - [Adam Kariv](https://github.com/akariv) - Engineering Lead at Open Knowledge International, Tech Lead on OpenSpending
  - [Paul Walsh](https://github.com/pwalsh) - Chief Product Officer at Open Knowledge International
- Any communication around the grant agreement should be directly done by email with Jo Barratt, Frictionless Data Project Manager

**Comment by roll** [comment]
Some low-level notes:
- reference implementations of `Profile` class - https://github.com/frictionlessdata/datapackage-js/blob/master/src/profile.js (Python version has some old code not really fully used)

**Comment by loleg** [comment]
Thanks @roll @pwalsh for this, really helps to have wayposts.

**Comment by scls19fr** [comment]
Hello,

to create a sample Julia project you should use `PkgDev`

```julia
Pkg.add("PkgDev")
using PkgDev
PkgDev.generate("Datapackages", "MIT")
```
This sample project will be generated and you will have sample unit tests.
Badge for Travis, coverage...

Kind regards

**Comment by scls19fr** [comment]
You should notice that most Julia package use plural in their name and their Github repository url finish using `.jl` (not `-jl`).
Julia users like package name with CamelCase

**Comment by roll** [comment]
@scls19fr 
Thanks!

Related to repo naming - it's because of the Github org standard.

**Comment by scls19fr** [comment]
https://github.com/davidanthoff/IterableTables.jl from @davidanthoff and https://github.com/davidanthoff/IterableTables.jl from @quinnj are probably related projects to consider

**Comment by scls19fr** [comment]
https://github.com/JuliaData/DataStreams.jl from @quinnj ... sorry

**Comment by loleg** [comment]
I came across this shortcut last night in the docs. Thanks very much for
pointing it out @scls19fr ~ glad to have someone already watching this
project :-)

Am 17.11.2017 12:07 schrieb "scls19fr" <notifications@github.com>:

Hello,

to create a sample Julia project you should use PkgDev

Pkg.add("PkgDev")using PkgDev
PkgDev.generate("Datapackages", "MIT")

This sample project will be generated and you will have sample unit tests.
Badge for Travis, coverage...

Kind regards

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/frictionlessdata/datapackage-jl/issues/1#issuecomment-345214983>,
or mute the thread

**Comment by scls19fr** [comment]
Some other projects that may be related to DataPackage.jl and could be add to wiki

Queryverse https://github.com/davidanthoff/Queryverse.jl

And for downloading / caching data
https://github.com/oxinabox/DataDeps.jl
https://github.com/helgee/RemoteFiles.jl
https://github.com/JuliaPackaging/BinaryProvider.jl

**Comment by oxinabox** [comment]
At some point we should talk. Will you be at juliacon?

**Comment by scls19fr** [comment]
Unfortunately I won't be there

**Comment by roll** [comment]
@loleg 
I'm closing meta issue as this stage is far behind us. Let's just use individual issues for everything left/reported/etc
